import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Image from 'next/image'
import {useRouter} from 'next/navigation'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'CareeBee',
  description: 'Generated by CareeBee',
  icons:{
    icon:'/assets/logo.png'
  }
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  )
  }
