'use client'
import Def from './def'
import CustomList from './customList'

export default function PrivacyPolicy() {
  return (
    <div className="mx-auto max-w-[900px] p-12">
      <div className="text-lg">
        This Policy does not apply to third-party applications, websites,
        products, services or platforms that may be accessed through (non-)
        links that we may provide to you. These sites are owned and operated
        independently from us, and they have their own separate privacy and data
        collection practices. Any Personal Data that you provide to these
        websites will be governed by the third-party’s own privacy policy. We
        cannot accept liability for the actions or policies of these independent
        sites, and we are not responsible for the content or privacy practices
        of such sites.
      </div>
      <div>
        <div className="pt-10 text-2xl font-semibold">Introduction</div>
        <div className="pt-4 text-lg">
          <div>
            Our Privacy Policy governs your visit to https://wonmo.donna.net/
            and explains how we collect, safeguard and disclose information that
            results from your use of our Service.{' '}
          </div>
          <div className="pt-8">
            We use your data to provide and improve Donna. By using Donna, you
            agree to the collection and use of information in accordance with
            this policy. Unless otherwise defined in this Privacy Policy, the
            terms used in this Privacy Policy have the same meanings as in our
            Terms and Conditions.
          </div>
          <div className="pt-8">
            Our Terms and Conditions (“Terms”) govern all use of Donna and
            together with the Privacy Policy constitute your agreement with us
            (“Agreement”).
          </div>
        </div>
        <div>
          <div className="pt-10 text-2xl font-semibold">Definitions</div>
          <Def
            title="SERVICE"
            content="means the https://wonmo.donna.net/ website operated by Wonmo, INC"
          ></Def>
          <Def
            title="PERSONAL DATA"
            content="means data about a living individual who can be identified from those data (or from those and other information either in our possession or likely to come into our possession)."
          ></Def>
          <Def
            title="USAGE DATA"
            content="is data collected automatically either generated by the use of Donna or from the Donna infrastructure itself (for example, the duration of a page visit)."
          ></Def>
          <Def
            title="COOKIES"
            content="are small files stored on your device (computer or mobile device)."
          ></Def>
          <Def
            title="DATA CONTROLLER"
            content="means a natural or legal person who (either alone or jointly or in common with other persons) determines the purposes for which and the manner in which any personal data are, or are to be, processed. For the purpose of this Privacy Policy, we are a Data
            Controller of your data."
          ></Def>
          <Def
            title="DATA PROCESSORS (OR SERVICE PROVIDERS)"
            content="means any natural or legal person who processes the data on behalf of the Data Controller. We may use the services of various
            Service Providers in order to process your data more effectively."
          ></Def>
          <Def
            title="DATA SUBJECT"
            content="is any living individual who is the subject of Personal Data."
          ></Def>
          <Def
            title="THE USER"
            content="is the individual using Donna. The User corresponds to the Data Subject, who is the subject of Personal Data."
          ></Def>
        </div>
        <div>
          <div className="pt-10 text-2xl font-semibold">
            Information Collection and Use with Third-Parties
          </div>
          <div className="list-decimal text-lg pt-4">
            <CustomList
              title="Purpose of Sharing:"
              descriptionList={[
                'Service Enhancement: We may share your data with third parties to enhance the functionality and efficiency of our Service.',
                'Legal Compliance: In certain circumstances, we may be required to share your data in compliance with legal obligations or in response to lawful requests by public authorities.',
              ]}
            />
            <CustomList
              title="Types of Third Parties:"
              descriptionList={[
                'Analytics Providers: For analyzing service usage and improving user experience.',
                'Marketing Partners: For targeted advertising and promotional campaigns.',
                'Cloud Storage Providers: For secure data storage and backup.',
                'Payment Processors:  For processing transactions securely.',
                "Foundation Model Providers: When you add Donna to an email, we use OpenAI’s GPT models to parse the thread. This enables us to take the correct action on your behalf. Any information in the emails that Donna is cc'd on will be shared with OpenAI. OpenAI's use of your personal information is governed by their Privacy Policy, which can be found at  OpenAI Privacy Policy",
              ]}
            />
            <CustomList
              title="Safeguards in Place:"
              descriptionList={[
                'Data Protection Agreements: We enter into data protection agreements with all third-party service providers, ensuring they adhere to our privacy standards.',
                'Limited Access: Access to your personal data is limited to what is necessary for the third party to perform their specific function.',
                'Regular Audits: We conduct regular audits of our third-party partners to ensure ongoing compliance with our privacy standards.',
              ]}
            />
            <CustomList
              title="User Consent and Opt-Out Options:"
              descriptionList={[
                'Explicit Consent: We obtain explicit consent from users before sharing any sensitive personal data with third parties.',
                'Opt-Out Options: Users have the option to opt out of certain types of data sharing. Instructions for opting out are clearly provided in our Service.',
              ]}
            />
            <CustomList
              title="Transparency:"
              descriptionList={[
                'List of Third Parties: A list of third-party service providers we share data with is available upon request.',
                'Updates on Changes: We will inform users of any significant changes in our data-sharing practices.',
              ]}
            />
            <CustomList
              title="International Data Transfers:"
              descriptionList={[
                'Cross-Border Data Transfer: If personal data is transferred to a third party in a different country, we ensure appropriate safeguards are in place in compliance with applicable data protection laws.',
              ]}
            />
            <CustomList
              title="User Data Rights:"
              descriptionList={[
                'Access to Shared Data:  Users have the right to know what personal data is shared with third parties and can request access to such information.',
                'Revocation of Consent:  Users can revoke consent to share their data with third parties at any time.',
              ]}
            />
          </div>
        </div>
      </div>
    </div>
  )
}
